import type { editor } from "monaco-editor";

/**
 * daedalus-noir — Monaco theme: full VS Code Dark+ syntax color on Daedalus's
 * matte-black ground. The app chrome stays greyscale+red; code gets real color.
 */
export const daedalusNoir: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "d4d4d4" },
    { token: "comment", foreground: "6a9955", fontStyle: "italic" },
    { token: "keyword", foreground: "569cd6" },
    { token: "keyword.flow", foreground: "c586c0" },
    { token: "keyword.control", foreground: "c586c0" },
    { token: "keyword.json", foreground: "569cd6" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "number", foreground: "b5cea8" },
    { token: "string", foreground: "ce9178" },
    { token: "string.escape", foreground: "d7ba7d" },
    { token: "regexp", foreground: "d16969" },
    { token: "type", foreground: "4ec9b0" },
    { token: "type.identifier", foreground: "4ec9b0" },
    { token: "namespace", foreground: "4ec9b0" },
    { token: "function", foreground: "dcdcaa" },
    { token: "identifier", foreground: "9cdcfe" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "variable.predefined", foreground: "4fc1ff" },
    { token: "constant", foreground: "4fc1ff" },
    { token: "tag", foreground: "569cd6" },
    { token: "metatag", foreground: "569cd6" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "ce9178" },
    { token: "attribute.value.number.css", foreground: "b5cea8" },
    { token: "attribute.value.unit.css", foreground: "b5cea8" },
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "delimiter.html", foreground: "808080" },
    { token: "key", foreground: "9cdcfe" },
    { token: "string.key.json", foreground: "9cdcfe" },
    { token: "string.value.json", foreground: "ce9178" },
    { token: "annotation", foreground: "dcdcaa" },
    { token: "invalid", foreground: "f44747" },
  ],
  colors: {
    "editor.background": "#111111",
    "editor.foreground": "#d4d4d4",
    "editorLineNumber.foreground": "#3d3d3d",
    "editorLineNumber.activeForeground": "#8a8a8a",
    "editorCursor.foreground": "#e5484d",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#3a3d4166",
    "editor.lineHighlightBackground": "#161616",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background1": "#1c1c1c",
    "editorIndentGuide.activeBackground1": "#3d3d3d",
    "editorWhitespace.foreground": "#1c1c1c",
    "editorGutter.background": "#111111",
    "editorWidget.background": "#161616",
    "editorWidget.border": "#262626",
    "editorHoverWidget.background": "#1c1c1c",
    "editorHoverWidget.border": "#262626",
    "editorSuggestWidget.background": "#161616",
    "editorSuggestWidget.border": "#262626",
    "editorSuggestWidget.selectedBackground": "#264f78",
    "editorBracketMatch.background": "#264f7844",
    "editorBracketMatch.border": "#569cd6",
    "editor.findMatchBackground": "#515c6a",
    "editor.findMatchHighlightBackground": "#ea5c0055",
    "scrollbarSlider.background": "#26262699",
    "scrollbarSlider.hoverBackground": "#3d3d3d",
    "scrollbarSlider.activeBackground": "#5a5a5a",
    focusBorder: "#e5484d",
    // Diff colors — VS Code-style green additions / red removals.
    "diffEditor.insertedTextBackground": "#9ccc2c33",
    "diffEditor.removedTextBackground": "#ff000033",
    "diffEditor.insertedLineBackground": "#9bb95533",
    "diffEditor.removedLineBackground": "#ff000022",
    "diffEditor.border": "#262626",
    "diffEditorGutter.insertedLineBackground": "#9bb95540",
    "diffEditorGutter.removedLineBackground": "#ff000030",
    "diffEditorOverview.insertedForeground": "#9bb955",
    "diffEditorOverview.removedForeground": "#f14c4c",
  },
};

/** Concrete mono stack for Monaco (var() is unreliable for glyph measuring). */
export const EDITOR_FONT =
  '"Cascadia Mono", "Cascadia Code", Consolas, "SF Mono", Menlo, "DejaVu Sans Mono", monospace';
